Repository Cian911/gomerge, pull requests merged in 2022-10, with the labels that each got.

#57 BUG: Fix bug in close operation
  pkg/cli/gomerge/gomerge.go
  pkg/cli/list/list.go
  pkg/gitclient/client.go
  pkg/utils/config_test.yaml
Labels: bug, enhancement

#58 DOCS: Update docs for 3.1.0 release.
  README.md
Labels: documentation

#59 Add Go linter
  .github/workflows/test.yml
Labels: good first issue, Hacktoberfest
